spring:
  jpa:
    open-in-view: false
    hibernate.ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    show_sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: <CLIENT-ID>
            client-secret: <CLIENT-SECRET>
server:
  port: 8089
